---
language: c
script: ./autogen.sh && make all check distcheck
sudo: false
addons:
  apt:
    packages:
      - gtk-doc-tools
compiler:
  - clang
  - gcc
after_failure:
  - test -f test-suite.log && cat test-suite.log
  - test -f osxcart-1.1/_build/test-suite.log && cat osxcart-1.1/_build/test-suite.log